// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/get-company.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "N\xE3o autenticado. Conecte sua conta Contuit novamente." }],
    isError: true
  };
}
async function resolveCompany(ctx) {
  const supabase = supabaseForUser(ctx);
  const { data, error } = await supabase.from("companies").select("id, name, industry, employee_count, monthly_revenue, goals").eq("user_id", ctx.getUserId()).order("created_at", { ascending: true }).limit(1).maybeSingle();
  if (error) throw new Error(error.message);
  return { supabase, company: data };
}

// src/lib/mcp/tools/get-company.ts
var get_company_default = defineTool({
  name: "get_company",
  title: "Get company profile",
  description: "Return the signed-in user's company profile (name, industry, employees, goals).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const { company } = await resolveCompany(ctx);
    if (!company) {
      return { content: [{ type: "text", text: "Nenhuma empresa cadastrada ainda." }] };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(company) }],
      structuredContent: { company }
    };
  }
});

// src/lib/mcp/tools/list-transactions.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";
var list_transactions_default = defineTool2({
  name: "list_transactions",
  title: "List transactions",
  description: "List the signed-in user's income and expense transactions, newest first.",
  inputSchema: {
    type: z.enum(["income", "expense"]).nullable().describe("Filter by transaction type, or null for both."),
    from: z.string().nullable().describe("Start date (YYYY-MM-DD) or null."),
    to: z.string().nullable().describe("End date (YYYY-MM-DD) or null."),
    limit: z.number().int().min(1).max(200).nullable().describe("Max rows (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ type, from, to, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const { supabase, company } = await resolveCompany(ctx);
    if (!company) return { content: [{ type: "text", text: "Nenhuma empresa cadastrada ainda." }] };
    let query = supabase.from("transactions").select("id, description, category, amount, type, date, payment_status, client_or_supplier").eq("company_id", company.id).order("date", { ascending: false }).limit(limit ?? 50);
    if (type) query = query.eq("type", type);
    if (from) query = query.gte("date", from);
    if (to) query = query.lte("date", to);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { transactions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-transaction.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var create_transaction_default = defineTool3({
  name: "create_transaction",
  title: "Create transaction",
  description: "Record a new income or expense transaction for the signed-in user's company.",
  inputSchema: {
    description: z2.string().trim().min(1).describe("What the transaction is for."),
    category: z2.string().trim().min(1).describe("Category, e.g. Marketing, Sal\xE1rios."),
    amount: z2.number().positive().describe("Amount in BRL."),
    type: z2.enum(["income", "expense"]).describe("income or expense."),
    date: z2.string().nullable().describe("Date (YYYY-MM-DD) or null for today."),
    payment_status: z2.enum(["paid", "pending"]).nullable().describe("Payment status or null for paid."),
    client_or_supplier: z2.string().nullable().describe("Client or supplier name, or null.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const { supabase, company } = await resolveCompany(ctx);
    if (!company) {
      return {
        content: [{ type: "text", text: "Cadastre sua empresa no Contuit antes de criar transa\xE7\xF5es." }],
        isError: true
      };
    }
    const { data, error } = await supabase.from("transactions").insert({
      company_id: company.id,
      description: input.description,
      category: input.category,
      amount: input.amount,
      type: input.type,
      date: input.date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10),
      payment_status: input.payment_status ?? "paid",
      client_or_supplier: input.client_or_supplier ?? null
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { transaction: data }
    };
  }
});

// src/lib/mcp/tools/financial-summary.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var financial_summary_default = defineTool4({
  name: "financial_summary",
  title: "Financial summary",
  description: "Summarize revenue, expenses, profit, margin and top expense categories for a period (default: last 30 days).",
  inputSchema: {
    days: z3.number().int().min(1).max(365).nullable().describe("Look-back window in days (default 30).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const { supabase, company } = await resolveCompany(ctx);
    if (!company) return { content: [{ type: "text", text: "Nenhuma empresa cadastrada ainda." }] };
    const window = days ?? 30;
    const from = new Date(Date.now() - window * 864e5).toISOString().slice(0, 10);
    const { data, error } = await supabase.from("transactions").select("amount, type, category, date").eq("company_id", company.id).gte("date", from);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const revenue = rows.filter((r) => r.type === "income").reduce((s, r) => s + Number(r.amount), 0);
    const expenses = rows.filter((r) => r.type === "expense").reduce((s, r) => s + Number(r.amount), 0);
    const profit = revenue - expenses;
    const margin = revenue > 0 ? profit / revenue * 100 : 0;
    const byCategory = /* @__PURE__ */ new Map();
    for (const r of rows) {
      if (r.type !== "expense") continue;
      byCategory.set(r.category, (byCategory.get(r.category) ?? 0) + Number(r.amount));
    }
    const topExpenseCategories = [...byCategory.entries()].map(([name, value]) => ({ name, value })).sort((a, b) => b.value - a.value).slice(0, 5);
    const summary = {
      company: company.name,
      periodDays: window,
      transactionCount: rows.length,
      revenue,
      expenses,
      profit,
      profitMargin: Number(margin.toFixed(1)),
      topExpenseCategories
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: { summary }
    };
  }
});

// src/lib/mcp/tools/list-invoices.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var list_invoices_default = defineTool5({
  name: "list_invoices",
  title: "List invoices",
  description: "List the signed-in user's invoices with amount, tax, status and due date.",
  inputSchema: {
    status: z4.string().nullable().describe("Filter by status (e.g. paid, pending) or null for all."),
    limit: z4.number().int().min(1).max(200).nullable().describe("Max rows (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const { supabase, company } = await resolveCompany(ctx);
    if (!company) return { content: [{ type: "text", text: "Nenhuma empresa cadastrada ainda." }] };
    let query = supabase.from("invoices").select("id, invoice_number, amount, tax_amount, status, issued_at, due_date, client_id").eq("company_id", company.id).order("issued_at", { ascending: false }).limit(limit ?? 50);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { invoices: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-recurring.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^3.25.76";
var list_recurring_default = defineTool6({
  name: "list_recurring_transactions",
  title: "List recurring commitments",
  description: "List recurring income and expenses (salaries, rent, subscriptions) with next execution dates.",
  inputSchema: {
    only_active: z5.boolean().nullable().describe("Return only active recurrences (default true).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ only_active }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const { supabase, company } = await resolveCompany(ctx);
    if (!company) return { content: [{ type: "text", text: "Nenhuma empresa cadastrada ainda." }] };
    let query = supabase.from("recurring_transactions").select("id, description, category, amount, type, frequency, next_execution_date, is_active").eq("company_id", company.id).order("next_execution_date", { ascending: true });
    if (only_active ?? true) query = query.eq("is_active", true);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { recurring: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "vdjwywrtobhqpbbpvogr";
var mcp_default = defineMcp({
  name: "contuit-ai-finance-copilot",
  title: "Contuit: AI Finance Copilot",
  version: "0.1.0",
  instructions: "Ferramentas financeiras do Contuit para a empresa do usu\xE1rio autenticado. Use financial_summary para vis\xE3o geral de receita, despesas e margem; list_transactions e list_invoices para detalhes; list_recurring_transactions para compromissos futuros; create_transaction para registrar receitas ou despesas. Valores em BRL.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_company_default,
    financial_summary_default,
    list_transactions_default,
    create_transaction_default,
    list_invoices_default,
    list_recurring_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
